# Работа с ClickHouse - Основы

Импорты

In [3]:
from clickhouse_connect import get_client
from clickhouse_connect.driver.httpclient import HttpClient as ClientCH
import pandas as pd

Подключение

In [4]:
# Подключение к ClickHouse с настройками для официального образа
CH_CLIENT = get_client(
    host='localhost',
    port=8123,
    username='default',
    password='password',
    database='default'
)

Функции для работы

In [5]:
def execute_query(
    query: str, 
    client: ClientCH = CH_CLIENT
) -> pd.DataFrame:
    """
    Simple function to execute a query and return the result as a pandas DataFrame
    """
    result = client.query(query)
    return pd.DataFrame(result.result_rows, columns=result.column_names)

Посмотрим на БД по умолчанию

In [6]:
q = """
SHOW DATABASES
"""
execute_query(q)

                 name
0  INFORMATION_SCHEMA
1             default
2  information_schema
3              system

Создадим свою БД

In [7]:
q = """
CREATE DATABASE IF NOT EXISTS test_database
"""
execute_query(q)

,read_rows,read_bytes,written_rows,written_bytes,total_rows_to_read,result_rows,result_bytes,elapsed_ns,query_id
0,0,0,0,0,0,0,0,10210480,66e9e8fa-2a33-4cc0-ae18-d9aa7e5c2a8b

Создадим таблицу

In [8]:
q = """
CREATE TABLE IF NOT EXISTS test_database.test_table (
    id UInt64 NOT NULL,
    name String,
    PRIMARY KEY id
)
"""
execute_query(q)

,read_rows,read_bytes,written_rows,written_bytes,total_rows_to_read,result_rows,result_bytes,elapsed_ns,query_id
0,0,0,0,0,0,0,0,14621741,291f7069-fa13-4086-8815-1da0f84da546

Посмотрим на таблички в нашей БД

In [9]:
q = """
SHOW TABLES FROM test_database
"""
execute_query(q)

         name
0  test_table

Загрузим данные

In [10]:
q = """
INSERT INTO test_database.test_table (id, name) 
VALUES
    (1, 'Otus'),
    (2, 'Test'),
"""
execute_query(q)

Empty DataFrame
Columns: []
Index: []

Сделаем выборку из нашей таблички

In [11]:
q = """
SELECT * FROM test_database.test_table
"""
execute_query(q)

   id  name
0   1  Otus
1   2  Test